# Arithmetic Operations on Array

In [2]:
import numpy as np

var = np.array([1,2,3,4])

var_add = var + 3

print(var_add)

[4 5 6 7]


In [4]:
var = np.array([1,2,3,4])

var_sub = var - 3

print(var_sub)

[-2 -1  0  1]


In [5]:
var = np.array([1,2,3,4])

var_mul = var * 3

print(var_mul)

[ 3  6  9 12]


In [6]:
var = np.array([1,2,3,4])

var_div = var / 3

print(var_div)

[0.33333333 0.66666667 1.         1.33333333]


In [7]:
var = np.array([1,2,3,4])

var_mod = var % 3

print(var_mod)

[1 2 0 1]


In [13]:
var = np.array([1,2,3,4])

# var_reciprocal = 1/var
var_reciprocal = np.reciprocal(var)

print(var_reciprocal)

[1 0 0 0]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

var_add = var1 + var2

print(var_add)

[ 6  8 10 12]


### Arithmetic functions in numpy

In [8]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

var_add = np.add(var1,var2)

print(var_add)

[ 6  8 10 12]


# 2D array

In [11]:
var2_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
var2_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

var_add2 = var2_1 + var2_2

print(var_add2)

[[ 2  4  6  8]
 [10 12 14 16]]
