# Iteration

In [1]:
import numpy as np

var = np.array([1,2,3,4,5,6,7,8,9])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5 6 7 8 9]

1
2
3
4
5
6
7
8
9


In [3]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])
print(var2)
print()
for i in var2:
    print(i)
print()

for i in var2:
    for j in i:
        print(j)
    print()

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4

5
6
7
8



In [8]:
var3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]])

print(var3)
print()

for i in var3:
    for j in i:
        for k in j:
            print(k)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


## Using nditer()

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
for i in np.nditer(arr, flags=['buffered'], op_dtypes=["S"]):
    print(i)

[[1 2 3]
 [4 5 6]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


## Using ndenumerate()

In [13]:
arr2 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]])

print(arr2)
print()
for i,d in np.ndenumerate(arr2):
    print(i,d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
(2, 0, 0) 13
(2, 0, 1) 14
(2, 0, 2) 15
(2, 1, 0) 16
(2, 1, 1) 17
(2, 1, 2) 18
