# Join Array

In [2]:
import numpy as np

arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])

ar = np.concatenate((arr, arr1))
print(ar)

[1 2 3 4 5 6 7 8]


In [9]:
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5,6],[7,8]])

ar_new = np.concatenate((v1, v2), axis=1)
print(ar_new)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1, var_2), axis=1)

a_new1 = np.hstack((var_1, var_2))      # row
a_new2 = np.vstack((var_1, var_2))      # column
a_new3 = np.dstack((var_1, var_2))      # height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array

In [23]:
var3 = np.array([1,2,3,4,5,6,7,8,9])

print(var3)
print()

ar1 = np.array_split(var3, 3)

print(ar1)
print(type(ar1[0]))

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'numpy.ndarray'>
