# Search

In [4]:
import numpy as np

var = np.array([1,2,3,4,2,4,0,5,6,8,1,3,9])

x = np.where((var%2) == 0)

print(x)

(array([1, 3, 4, 5, 6, 8, 9], dtype=int64),)


In [11]:
var1 = np.array([1,2,3,4,5,6,7,8])

x1 = np.searchsorted(var1, 5)

print(x1)

4


# Sort

In [13]:
ar = np.array([5,6,8,6,8,6,1,9,8,7,8,4,0,6,8])

nw = np.sort(ar)

print(nw)

[0 1 4 5 6 6 6 6 7 8 8 8 8 8 9]


In [14]:
ar1 = np.array([[7,1,9], [6,2,8], [8,1,6]])

nw1 = np.sort(ar1)

print(nw1)

[[1 7 9]
 [2 6 8]
 [1 6 8]]


# Filter

In [15]:
ar2 = np.array(["a", "s", "d", "f"])

f = [True, False, False, True]

new_a = ar2[f]
print(new_a)

['a' 'f']


# Shuffle

In [19]:
arr1 = np.array([1,2,3,4,5])

np.random.shuffle(arr1)

print(arr1)

[3 1 5 2 4]


# Unique

In [23]:
arr2 = np.array([1,2,2,2,4,4,4,6,6,8,7,5,44,1,0,0, 3])

x = np.unique(arr2, return_index=True, return_counts=True)

print(x)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 44]), array([14,  0,  1, 16,  4, 11,  7, 10,  9, 12], dtype=int64), array([2, 2, 3, 1, 3, 1, 2, 1, 1, 1], dtype=int64))


# Resize

In [25]:
arr3 = np.array([1,2,3,4,5,6])

y = np.resize(arr3, (3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten and Ravel

In [28]:
arr4 = np.array([[1,2],[3,4],[5,6]])

print(arr4.flatten(order="F"))
print(arr4.ravel(order="F"))

[1 3 5 2 4 6]
[1 3 5 2 4 6]
