# Matrix

In [2]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [3]:
var1 = np.array([[1,2,3],[4,5,6]])

print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# Arithmetic Operations in Matrix

## Addition

In [4]:
var2 = np.matrix([[1,2,3],[4,5,6]])
var3 = np.matrix([[1,2,3],[4,5,6]])

print()
print(var2 + var3)


[[ 2  4  6]
 [ 8 10 12]]


## Subtraction

In [5]:
var2 = np.matrix([[1,2,3],[4,5,6]])
var3 = np.matrix([[1,2,3],[4,5,6]])

print()
print(var2 - var3)


[[0 0 0]
 [0 0 0]]


# Multiplication

In [8]:
var2 = np.matrix([[1,2],[4,5]])
var3 = np.matrix([[1,2],[4,5]])

print()
print(var2 * var3)
print()
print(var2.dot(var3))


[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


# Matrix Function In NumPy Array

## Transpose

In [11]:
var2 = np.matrix([[1,2,3],[4,5,6]])

print(var2)

print()

print(np.transpose(var2))

print()

print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [14]:
var2 = np.matrix([[1,2],[4,5]])

print(var2)

print()

print(np.swapaxes(var2, 0, 1))

[[1 2]
 [4 5]]

[[1 4]
 [2 5]]


## Inverse

In [15]:
var3 = np.matrix([[1,2],[4,5]])
print(var3)
print()
print(np.linalg.inv(var3))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


## Power

In [17]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()


print(np.linalg.matrix_power(var4, 3))
print()
print(np.linalg.matrix_power(var4, 0))
print()
print(np.linalg.matrix_power(var4, -3))

[[1 2]
 [3 4]]

[[ 37  54]
 [ 81 118]]

[[1 0]
 [0 1]]

[[-14.75    6.75 ]
 [ 10.125  -4.625]]


## Determinant

In [20]:
var5 = np.matrix([[1,2,3],[3,4,3],[5,6,7]])
print(var4)
print()

print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-7.999999999999998
