# Arrays

In [1]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
y = [1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


## Dimension of array

In [2]:
array = np.array([1,3,5,7,9])

print(array.ndim)

1


In [8]:
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
print(array2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
array3 = np.array([[[1,2,3,4],[1,4,7,9],[1,2,3,4]]])
print(array3)
print(array3.ndim)

[[[1 2 3 4]
  [1 4 7 9]
  [1 2 3 4]]]
3


In [14]:
arrayN = np.array([1,2,3,4,5], ndmin=10)
print(arrayN)
print(arrayN.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Creating NumPy Arrays in different ways

### Arrays filled with 0

In [20]:
import numpy as np

arr_zero = np.zeros(4)
print(arr_zero)

print()
#2 dimension array

print("2 Dimension :- ")
arr_zero1 = np.zeros((3,4))
print(arr_zero1)

[0. 0. 0. 0.]

2 Dimension :- 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Arrays filled with 1

In [22]:
arr_one = np.ones(5)
print(arr_one)

print()
#2 dimension array

print("2 Dimension :- ")
arr_one1 = np.ones((3,4))
print(arr_one1)

[1. 1. 1. 1. 1.]

2 Dimension :- 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Empty arrays

In [24]:
arr_empty = np.empty(4)
print(arr_empty)

[0. 0. 0. 0.]


### Array for range of elements

In [25]:
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


### Array with diagonal elements flled with 1

In [26]:
arr_diagonal = np.eye(3)
print(arr_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr_diagonal1 = np.eye(3,5)
print(arr_diagonal1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Array with values that are spaced linearly in a specified interval

In [34]:
arr_lin = np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]
