# Random Numbers in Array

# Rand()

### This function is used to generate a random value between 0 and 1

In [10]:
import numpy as np

var = np.random.rand(5)

print(var)

[0.9015306  0.94240911 0.91879775 0.0113213  0.43887779]


In [11]:
var1 = np.random.rand(2,5)

print(var1)

[[0.57737014 0.45867319 0.65077107 0.01266468 0.51204863]
 [0.0093536  0.21159908 0.59589252 0.71488    0.91603373]]


# Randn()

### This function is used to generate random value close to zero. This may return positive or negative number as well

In [12]:
var2 = np.random.randn(5)

print(var2)

[ 0.60068023  0.49577466  0.35022494  0.30161727 -1.67852665]


In [14]:
var3 = np.random.randn(3, 5)

print(var3)

[[ 0.28990753 -0.70832196  0.3236588   0.59071181 -0.14830892]
 [ 0.51545983  0.10871375 -0.20414516  0.74411198  1.64661142]
 [-0.12834476  1.69184544 -0.89812726  0.86881573 -0.21032065]]


# Ranf()

### This function is used for random sampling in NumPy. It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0)

In [21]:
var4 = np.random.ranf(4)

print(var4)

[0.88621291 0.69570184 0.8297101  0.47625384]


# Randint()

### The function is used to generate a random number in a given range

In [26]:
var5 = np.random.randint(5,30,7)

# (min, max, totalNumberOfValues)

print(var5)

[ 6 22  5 10 29 21 16]
