|  Sr. No.  |     Data Types      |                             Description                              |
|:---------:|:-------------------:|:--------------------------------------------------------------------:|
|     1     |        bool_        |                       Boolean stored as a byte                       |
|     2     |        int_         |                    Default integer type (as in C)                    |
|     3     |        intc         |                          identical to C int                          |
|     4     |        intp         |                      integer used for indexing                       |
|     5     |        int8         |                                 Byte                                 |
|     6     |        int16        |                      Integer (-32768 to 32767)                       |
|     7     |        int32        |                 Integer (-2147483648 to 2147483647)                  |
|     8     |        int64        |        Integer (-9223372036854775808 to 9223372036854775807)         |
|     9     |        uint8        |                     unsigned integer (0 to 255)                      |
|    10     |       uint16        |                    unsigned integer (0 to 65535)                     |
|    11     |       uint32        |                  unsigned integer (0 to 4294967295)                  |
|    12     |       uint64        |             unsigned integer (0 to 18446744073709551615)             |
|    13     |       float_        |                        shorthand for float64                         |
|    14     |       float16       |  Half precision float: sign bit, 5 bits exponent, 10 bits mantissa   |
|    15     |       float32       | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa  |
|    16     |       float64       | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
|    17     |      complex_       |                       shorthand for complex128                       |
|    18     |      complex64      |           complex number represented by two 32 bit floats            |
|    19     |      complex_       |            complex number represented y two 64 bit floats            |



In [2]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6, 10])

print("Data Type :", var.dtype)

Data Type : int32


In [3]:
var2 = np.array([1.6, 7.5, 6.2])

print("Data Type :", var2.dtype)

Data Type : float64


In [4]:
var3 = np.array(["A", "S", "K", "L"])

print("Data Type :", var3.dtype)

Data Type : <U1


In [5]:
var4 = np.array(["A", "S", "K", "L", 1, 5, 9, 7])

print("Data Type :", var4.dtype)

Data Type : <U11


## Changing Data Types Manually

In [6]:
x = np.array([1,2,3,4,5], dtype=np.int8)

print("Data Type :", x.dtype)

Data Type : int8


In [8]:
x1 = np.array([1,2,3,4,5], dtype="f")

print("Data Type :", x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4. 5.]


In [10]:
x2 = np.array([1,2,3,4,5])

new = np.float32(x2)

new_one = np.int_(new)

print("x2 = ", x2)
print("Data Type :", x2.dtype)

print("new = ", new)
print("Data Type :", new.dtype)

print("new_one = ", new_one)
print("Data Type :", new_one.dtype)

x2 =  [1 2 3 4 5]
Data Type : int32
new =  [1. 2. 3. 4. 5.]
Data Type : float32
new =  [1 2 3 4 5]
Data Type : int32


In [12]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)


[1 2 3 4]
[1. 2. 3. 4.]
