# Shape

In [2]:
import numpy as np

arr = np.array([[1,2],[1,2]])

print(arr)
print()
print("Shape = ", arr.shape)

[[1 2]
 [1 2]]

Shape =  (2, 2)


In [4]:
arr1 = np.array([1,2,3,4], ndmin=4)

print(arr1)

print("ndim = ", arr1.ndim)
print()
print("shape = ", arr1.shape)

[[[[1 2 3 4]]]]
ndim =  4

shape =  (1, 1, 1, 4)


# Reshape

In [10]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2)
print(arr2.ndim)
print("shape = ", arr2.shape)

print()

x = arr2.reshape(3,3)

#   reshape( row, column)

print(x)
print(x.ndim)
print("shape = ", x.shape)

[1 2 3 4 5 6 7 8 9]
1
shape =  (9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
shape =  (3, 3)


In [13]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,1,2,3])
print(arr3)
print(arr3.ndim)
print("shape = ", arr3.shape)

print()

x1 = arr3.reshape(2,3,2)

#   reshape( row, column)

print(x1)
print(x1.ndim)
print("shape = ", x1.shape)

print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 7 8 9 1 2 3]
1
shape =  (12,)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [2 3]]]
3
shape =  (2, 3, 2)

[1 2 3 4 5 6 7 8 9 1 2 3]
1
