# Broadcasting in NumPy array

In [3]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])

print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### Broadcasting NumPy Arrays

(1) Same Dimension
(2) Atleast one "1" should be there   (1,3)    (3,1)   <-

In [9]:
var1 = np.array([1,2,3])
print(var1.shape)

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)

print()
print()
print("Sum = ")
print(var1 + var2)

(3,)
(3, 1)
[[1]
 [2]
 [3]]


Sum = 
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3], [1,2,3]])
print(y.shape)

print()
print(x)
print()
print(y)
print()
print(x+y)

(2, 1)
(2, 3)

[[1]
 [2]]

[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]
