# Indexing

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print()
print(arr[1])
print()
print(arr[-3])

[1 2 3 4 5]

[2 3]

[3 4 5]


In [15]:
arr1 = np.array([[1,2,3], [4,5,6]])

print(arr1)
print()
print("Dim = ", arr1.ndim)
print()
print(arr1[0,2])

[[1 2 3]
 [4 5 6]]

Dim =  2

3


In [21]:
arr3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print(arr3)
print()
print("Dim = ",arr3.ndim)
print()
print(arr3[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Dim =  3

4


# Slicing

### start : stop : step

In [24]:
import numpy as np

var = np.array([1,2,3,4,5,6])
print(var)
print()
print(var[1:4:2])

[1 2 3 4 5 6]

[2 4]


In [28]:
var2 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(var2)
print()
print(var2[1,2:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[ 8  9 10]
