# Insert

In [3]:
import numpy as np

var = np.array([1,2,3,4])

print(var)

v = np.insert(var, (2,4) , 40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [9]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1, 2, [22,23,24], axis=0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [10]:
var = np.array([1,2,3,4])

print(var)

x = np.append(var, 12.5)

print(x)

[1 2 3 4]
[ 1.   2.   3.   4.  12.5]


# Delete

In [11]:
var3 = np.array([1,2,3,4])

print(var3)

d = np.delete(var3, 2)
print(d)

[1 2 3 4]
[1 2 4]
